utils::globalVariables(c("valid_blood_groups", "valid_blood_groups",
                         "valid_tiers", "valid_rris",
                         "candidates", "urgent", "cPRA", "dialysis",
                         "cabs", "hlaApt", "hlaBpt", "hlaDRpt",
                         "ABOpt", "ID", "bg", "A1",
                         "A2", "B1", "B2", "DR1", "DR2",
                         "age", "dialysis", "MMP", "SP",
                         "AM", "mmA", "mmB", "mmDR",
                         "pointsHLA", "pointsDial", "compBlood", "xm",
                         "pointsET", "donor_age", "HI", "mm000", "pointsETx"
                         ,"A", "freq", "B", "DR", "desc",
                         "ptsHLA", "ptsPRA", "ptsage", "ptsdial", "ptsPT", "",
                         "candidates.uk", "Tier", "MS", "points.hla.age", "matchability", "points.age",
                         "total.HLA", "points.abo", "pointsUK", ".", ":=",
                         "row_n",
                         "res","read.csv",
                         "A1_freq","A2_freq",
                         "B1_freq","B2_freq",
                         "DR1_freq","DR2_freq",
                         "MMP0","MMP2",
                         "MMP1","level",
                         "donors","dABO","dA","dB","dDR","donor.age",
                         "algorithm", "recipient.dialysis", "donors.uk", "check.validity"
                         ))
